### ISSUE TITLE
"The Phone number +085236725506 isn't on Whatsapp" error coming when in mobile devices

### ISSUE THREAD

**Issue by fasilkks** [dsasmita/magento2-whatsapp-chat#1]
Hi friends, 
After all the installation and configuration of the module,   i open the configured website using a mobile device (safari browser )  . the whatsapp open on clicking the icon in website  , but with error "The Phone number +085236725506 isn't on  Whatsapp" . but in desktop website the whatsapp open with configured whatsapp number. any body have the same issue , any solution for it?
thanks

**Comment by brcastro** [comment]
> Hi friends,
> After all the installation and configuration of the module, i open the configured website using a mobile device (safari browser ) . the whatsapp open on clicking the icon in website , but with error "The Phone number +085236725506 isn't on Whatsapp" . but in desktop website the whatsapp open with configured whatsapp number. any body have the same issue , any solution for it?
> thanks

Hi, @fasilkks. I hope it's not too late.
This happens because this number is hardcoded on line 9 of button.phtml.
You need to change this
`<a href="https://wa.me/085236725506?text=<?php echo $helper->getMessage(); ?>" onclick="gtag('event', 'WhatsApp', {'event_action': 'whatsapp_chat', 'event_category': 'Chat', 'event_label': 'Chat_WhatsApp'});" target="_blank" class="btn-mobile">
`
 
to this

`<a href="https://wa.me/<?php echo $helper->getPhone(); ?>?text=<?php echo $helper->getMessage(); ?>" onclick="gtag('event', 'WhatsApp', {'event_action': 'whatsapp_chat', 'event_category': 'Chat', 'event_label': 'Chat_WhatsApp'});" target="_blank" class="btn-mobile">`
